### ISSUE TITLE
CheckList

### ISSUE THREAD

**Issue by ArthurLLima97** [ArthurLLima97/Biblioteca#1]
- [x] Clonar o repositório
- [x] criar um arquivo com o programa 
- [x] Editar o código para criar um main()
- [x] Apresentar a mensagem inicial do sistema com cout
- [x] compilar o programa 
- [x] Testar o programa 
- [x] Salvar o programa com git.add.git commit e git push
